### ISSUE TITLE
Throws 404 Error

### ISSUE THREAD

**Issue by S0lll0s** [superboum/cleverbot#2]
Recently this broke, asking the bot something now throws a 404 error:

    >>> cleverbot.Session().Ask("hello there")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/s0lll0s/documents/stuff/htll/cleverbot.py", line 54, in Ask
        asw=self.Send()
      File "/home/s0lll0s/documents/stuff/htll/cleverbot.py", line 47, in Send
        with urllib.request.urlopen("http://www.cleverbot.com/webservicemin",binary_data,5000) as url:
      File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.4/urllib/request.py", line 469, in open
        response = meth(req, response)
      File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python3.4/urllib/request.py", line 507, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found

Could we get a fix for that by any chance?

**Comment by superboum** [comment]
Yep, cleverbot seems to need a cookie now. Currently working on a fix. Stay tuned !

**Comment by superboum** [comment]
Fixed in 5297baa 
Let me know if it still doesn't work for you !

**Comment by S0lll0s** [comment]
nope, it's working again, thanks for the quick fix!
